/*******************************************************************************
 * eiptargetservice.cpp - Reusable EtherNet/IP Target (Adapter) service
 ******************************************************************************/

#include "eiptargetservice.h"
#include "eiptargetworker.h"

#include <QNetworkInterface>
#include <QDate>
#include <QTime>
#include <QTextStream>

extern "C" {
#include "devicedata.h"
}

EipTargetService::EipTargetService(QObject *parent)
    : QObject(parent)
{
    m_worker = new EipTargetWorker(this);

    // Forward worker signals
    connect(m_worker, &EipTargetWorker::started,
            this, &EipTargetService::started);
    connect(m_worker, &EipTargetWorker::stopped,
            this, &EipTargetService::stopped);
    connect(m_worker, &EipTargetWorker::errorOccurred,
            this, &EipTargetService::errorOccurred);
    connect(m_worker, &EipTargetWorker::logMessage,
            this, &EipTargetService::logMessage);
    connect(m_worker, &EipTargetWorker::ioConnectionEvent,
            this, &EipTargetService::ioConnectionEvent);
    connect(m_worker, &EipTargetWorker::outputDataReceived,
            this, &EipTargetService::outputDataReceived);
    connect(m_worker, &EipTargetWorker::ipConfigured,
            this, &EipTargetService::ipConfigured);
}

EipTargetService::~EipTargetService()
{
    stop();
}

bool EipTargetService::isRunning() const
{
    return m_worker->isRunning();
}

void EipTargetService::start(const QString &ifaceIndex)
{
    m_worker->setIoSizes(m_config.inputSize, m_config.outputSize);
    m_worker->start(ifaceIndex);
}

void EipTargetService::stop()
{
    m_worker->stop();
}

QByteArray EipTargetService::inputData() const
{
    return m_worker->inputData();
}

QByteArray EipTargetService::outputData() const
{
    return m_worker->outputData();
}

void EipTargetService::setInputData(const QByteArray &data)
{
    m_worker->setInputData(data);
}

/* static */
QList<EipNetworkInterface> EipTargetService::availableInterfaces()
{
    QList<EipNetworkInterface> result;
    const QList<QNetworkInterface> ifaces = QNetworkInterface::allInterfaces();
    for (const QNetworkInterface &iface : ifaces) {
        if (iface.flags() & QNetworkInterface::IsLoopBack) continue;
        if (!(iface.flags() & QNetworkInterface::IsUp)) continue;

        QString ipStr;
        for (const QNetworkAddressEntry &e : iface.addressEntries()) {
            if (e.ip().protocol() == QAbstractSocket::IPv4Protocol) {
                ipStr = e.ip().toString();
                break;
            }
        }
        if (ipStr.isEmpty()) continue;

        EipNetworkInterface ni;
        ni.index = iface.index();
        ni.name  = iface.humanReadableName();
        ni.ipAddress = ipStr;
        ni.displayLabel = QStringLiteral("%1 (%2) [idx:%3]")
                              .arg(ni.name).arg(ni.ipAddress).arg(ni.index);
        result.append(ni);
    }
    return result;
}

/* static */
QString EipTargetService::generateEds(int inSz, int outSz)
{
    // 使用默认的设备信息
    return generateEds(inSz, outSz,
                       QStringLiteral("QtEipTarget"),
                       OPENER_DEVICE_VENDOR_ID,
                       OPENER_DEVICE_NAME,
                       OPENER_DEVICE_PRODUCT_CODE,
                       OPENER_DEVICE_MAJOR_REVISION,
                       OPENER_DEVICE_MINOR_REVISION);
}

/* static */
QString EipTargetService::generateEds(int inSz, int outSz,
                                      const QString &vendorName, quint16 vendorID,
                                      const QString &productName, quint16 productCode,
                                      quint8 majorRev, quint8 minorRev)
{
    QString eds;
    QTextStream ts(&eds);

    ts << "$ EDS file generated by QtEipTarget\n";
    ts << "$ Input(T->O) Assembly 100: " << inSz << " bytes\n";
    ts << "$ Output(O->T) Assembly 150: " << outSz << " bytes\n";
    ts << "$ Config Assembly 151: 10 bytes\n\n";

    // [File]
    ts << "[File]\n";
    ts << "        DescText = \"" << productName << " EtherNet/IP Adapter\";\n";
    ts << "        CreateDate = " << QDate::currentDate().toString("MM-dd-yyyy") << ";\n";
    ts << "        CreateTime = " << QTime::currentTime().toString("HH:mm:ss") << ";\n";
    ts << "        ModDate = " << QDate::currentDate().toString("MM-dd-yyyy") << ";\n";
    ts << "        ModTime = " << QTime::currentTime().toString("HH:mm:ss") << ";\n";
    ts << "        Revision = 2.3;\n";
    ts << "        HomeURL = \"\";\n\n";

    // [Device]
    ts << "[Device]\n";
    ts << "        VendCode = " << vendorID << ";\n";
    ts << "        VendName = \"" << vendorName << "\";\n";
    ts << "        ProdType = " << OPENER_DEVICE_TYPE << ";\n";
    ts << "        ProdTypeStr = \"Communications Adapter\";\n";
    ts << "        ProdCode = " << productCode << ";\n";
    ts << "        MajRev = " << majorRev << ";\n";
    ts << "        MinRev = " << minorRev << ";\n";
    ts << "        ProdName = \"" << productName << "\";\n";
    ts << "        Catalog = \"" << productName << "\";\n\n";

    ts << "[Device Classification]\n";
    ts << "        Class1 = EtherNetIP;\n\n";

    // [Params]
    ts << "[Params]\n";
    ts << "        Param1 =\n";
    ts << "                0,                      $ reserved, shall equal 0\n";
    ts << "                ,,                      $ Link Path Size, Link Path\n";
    ts << "                0x0000,                 $ Descriptor\n";
    ts << "                0xD1,                   $ Data Type\n";
    ts << "                1,                      $ Data Size in bytes\n";
    ts << "                \"Input Data\",           $ name\n";
    ts << "                \"\",                     $ units\n";
    ts << "                \"\",                     $ help string\n";
    ts << "                ,,0,                    $ min, max, default data values\n";
    ts << "                ,,,,                    $ mult, div, base, offset scaling\n";
    ts << "                ,,,,                    $ mult, div, base, offset links\n";
    ts << "                ;                       $ decimal places\n";
    ts << "        Param2 =\n";
    ts << "                0,,,0x0000,0xD1,1,\"Output Data\",\"\",\"\",,,0,,,,,,,,;\n";
    ts << "        Param3 =\n";
    ts << "                0,,,0x0000,0xD1,1,\"Config Data\",\"\",\"\",,,0,,,,,,,,;\n";
    ts << "        Param4 =\n";
    ts << "                0,,,0x0000,0xC8,4,\"RPI\",\"\",\"\",20000,,30000,,,,,,,,;\n";
    // Param5: Production Inhibit Time (PIT) for COS connections, in milliseconds
    ts << "        Param5 =\n";
    ts << "                0,,,0x0000,0xC8,4,\"Production Inhibit Time\",\"ms\",\"\",5,,5000,,,,,,,,;\n";
    ts << "\n";

    // [Assembly]
    ts << "[Assembly]\n";
    ts << "        Object_Name = \"Assembly Object\";\n";
    ts << "        Object_Class_Code = 0x04;\n";
    ts << "        Number_Of_Static_Instances = 6;\n";

    ts << "        Assem100 =\n";
    ts << "                \"Input Assembly\",\n";
    ts << "                \"\",\n";
    ts << "                " << inSz << ",\n";
    ts << "                0x0000,\n";
    ts << "                ,,\n";
    for (int i = 0; i < inSz; i++) {
        ts << "                8,Param1";
        ts << ((i < inSz - 1) ? ",\n" : ";\n");
    }

    ts << "        Assem150 =\n";
    ts << "                \"Output Assembly\",\n";
    ts << "                \"\",\n";
    ts << "                " << outSz << ",\n";
    ts << "                0x0001,\n";
    ts << "                ,,\n";
    for (int i = 0; i < outSz; i++) {
        ts << "                8,Param2";
        ts << ((i < outSz - 1) ? ",\n" : ";\n");
    }

    ts << "        Assem151 =\n";
    ts << "                \"Config Assembly\",\n";
    ts << "                \"\",\n";
    ts << "                10,\n";
    ts << "                0x0001,\n";
    ts << "                ,,\n";
    for (int i = 0; i < 10; i++) {
        ts << "                8,Param3";
        ts << ((i < 9) ? ",\n" : ";\n");
    }
    ts << "\n";

    // [Connection Manager]
    ts << "[Connection Manager]\n";
    ts << "        Revision = 1;\n";
    ts << "        Object_Name = \"Connection Manager Object\";\n";
    ts << "        Object_Class_Code = 0x06;\n";
    ts << "        MaxInst = 1;\n";
    ts << "        Number_Of_Static_Instances = 1;\n";
    ts << "        Max_Number_Of_Dynamic_Instances = 0;\n";

    ts << "        Connection1 =\n";
    ts << "                0x84030002,             $ trigger/transport: exclusive-owner, cyclic+COS, class 1\n";
    ts << "                0x44640405,             $ O->T: fixed, P2P; T->O: fixed, multicast+P2P\n";
    ts << "                Param4,,Assem150,       $ O->T RPI, size, format\n";
    ts << "                Param4,,Assem100,       $ T->O RPI, size, format\n";
    ts << "                ,,                      $ config #1 size, format\n";
    ts << "                ,Assem151,              $ config #2 size, format\n";
    ts << "                \"Exclusive Owner\",      $ Connection Name\n";
    ts << "                \"\",                     $ help string\n";
    ts << "                \"20 04 24 97 2C 96 2C 64\";    $ Path\n";

    ts << "        Connection2 =\n";
    ts << "                0x02030002,             $ trigger/transport: input-only, cyclic+COS, class 1\n";
    ts << "                0x44640305,             $ O->T: fixed; T->O: fixed+variable, multicast+P2P\n";
    ts << "                Param4,0,,              $ O->T RPI, size=0 (heartbeat), format\n";
    ts << "                Param4," << inSz << ",Assem100,     $ T->O RPI, size, format\n";
    ts << "                ,,                      $ config #1 size, format\n";
    ts << "                0,,                     $ config #2 size, format\n";
    ts << "                \"Input Only\",           $ Connection Name\n";
    ts << "                \"\",                     $ help string\n";
    ts << "                \"20 04 24 97 2C 98 2C 64\";    $ Path\n";

    ts << "        Connection3 =\n";
    ts << "                0x01030002,             $ trigger/transport: listen-only, cyclic+COS, class 1\n";
    ts << "                0x44240305,             $ O->T: fixed; T->O: variable, multicast+P2P\n";
    ts << "                Param4,0,,              $ O->T RPI, size=0 (heartbeat), format\n";
    ts << "                Param4,,Assem100,       $ T->O RPI, size, format\n";
    ts << "                ,,                      $ config #1 size, format\n";
    ts << "                ,,                      $ config #2 size, format\n";
    ts << "                \"Listen Only\",          $ Connection Name\n";
    ts << "                \"\",                     $ help string\n";
    ts << "                \"20 04 24 97 2C 99 2C 64\";    $ Path\n";
    ts << "\n";

    // [Capacity]
    ts << "[Capacity]\n";
    ts << "        MaxMsgConnections = 6;\n";
    ts << "        MaxIOProduceConsume = 2;\n";
    ts << "        MaxIOMcastProducers = 1;\n";
    ts << "        MaxIOMcastConsumers = 1;\n";
    ts << "        MaxConsumersPerMcast = 6;\n";
    ts << "        TSpec1 = TxRx, " << qMax(inSz, outSz) << ", 100;\n\n";

    ts << "[TCP/IP Interface Class]\n";
    ts << "        Revision = 4;\n";
    ts << "        Object_Name = \"TCP/IP Interface Object\";\n";
    ts << "        Object_Class_Code = 0xF5;\n";
    ts << "        MaxInst = 1;\n";
    ts << "        Number_Of_Static_Instances = 1;\n";
    ts << "        Max_Number_Of_Dynamic_Instances = 0;\n\n";

    ts << "[Ethernet Link Class]\n";
    ts << "        Revision = 4;\n";
    ts << "        Object_Name = \"Ethernet Link Object\";\n";
    ts << "        Object_Class_Code = 0xF6;\n";
    ts << "        MaxInst = 1;\n";
    ts << "        Number_Of_Static_Instances = 1;\n";
    ts << "        Max_Number_Of_Dynamic_Instances = 0;\n\n";

    ts << "[Identity Class]\n";
    ts << "        Revision = 1;\n";
    ts << "        Object_Name = \"Identity Object\";\n";
    ts << "        Object_Class_Code = 0x01;\n";
    ts << "        MaxInst = 1;\n";
    ts << "        Number_Of_Static_Instances = 1;\n";
    ts << "        Max_Number_Of_Dynamic_Instances = 0;\n\n";

    ts << "[QoS Class]\n";
    ts << "        Revision = 1;\n";
    ts << "        Object_Name = \"QoS Object\";\n";
    ts << "        Object_Class_Code = 0x48;\n";
    ts << "        MaxInst = 1;\n";
    ts << "        Number_Of_Static_Instances = 1;\n";
    ts << "        Max_Number_Of_Dynamic_Instances = 0;\n";

    return eds;
}
